### ISSUE TITLE
Exception in thread "main" retrofit2.adapter.rxjava2.HttpException: HTTP 429 

### ISSUE THREAD

**Issue by wufug** [HamaWhiteGG/langchain-java#63]
ChatAgentExample

Exception in thread "main" retrofit2.adapter.rxjava2.HttpException: HTTP 429 
	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:57)
	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:38)
	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:48)
	at io.reactivex.Observable.subscribe(Observable.java:10151)
	at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:35)
	at io.reactivex.Observable.subscribe(Observable.java:10151)
	at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
	at io.reactivex.Single.subscribe(Single.java:2517)
	at io.reactivex.Single.blockingGet(Single.java:2001)
	at com.hw.openai.OpenAiClient.create(OpenAiClient.java:237)
	at com.hw.langchain.chat.models.openai.ChatOpenAI._generate(ChatOpenAI.java:174)
	at com.hw.langchain.chat.models.base.BaseChatModel.lambda$generate$0(BaseChatModel.java:53)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at com.hw.langchain.chat.models.base.BaseChatModel.generate(BaseChatModel.java:54)
	at com.hw.langchain.chat.models.base.BaseChatModel.generatePrompt(BaseChatModel.java:72)
	at com.hw.langchain.chains.llm.LLMChain.generate(LLMChain.java:111)
	at com.hw.langchain.chains.llm.LLMChain.innerCall(LLMChain.java:101)
	at com.hw.langchain.chains.base.Chain.call(Chain.java:103)
	at com.hw.langchain.chains.llm.LLMChain.predict(LLMChain.java:164)
	at com.hw.langchain.agents.agent.Agent.plan(Agent.java:109)
	at com.hw.langchain.agents.agent.AgentExecutor.takeNextStep(AgentExecutor.java:112)
	at com.hw.langchain.agents.agent.AgentExecutor.innerCall(AgentExecutor.java:153)
	at com.hw.langchain.chains.base.Chain.call(Chain.java:103)
	at com.hw.langchain.chains.base.Chain.call(Chain.java:89)
	at com.hw.langchain.chains.base.Chain.run(Chain.java:171)
	at com.hw.langchain.examples.agents.ChatAgentExample.main(ChatAgentExample.java:53)

**Comment by HamaWhiteGG** [comment]
Please check #43 to see if it can help with your issue.
